### ISSUE TITLE
 Intermittent error

### ISSUE THREAD

**Issue by enfold-josh** [enfold/pas.plugins.ldap#4] opened 2021-04-27 19:27 UTC
We are seeing the error below intermittently but often enough that you can click around the site a few times to reproduce it. I don't know how this is happening but it looks like when the configure method on the region is called a second time the backend isn't replaced with a new one. Since the existing backend is a ProxyBackend it has no deserialiser or serialiser. The region then sets its own serialiser and deserialiser to the values from self.backend which are None. Because the deserialiser on the region is now None the values returned from redis are no longer deserialised. Looking at the code for CacheRegion.configure I do not see how this is possible. If replace_existing_backend is False you should get an exception and if it is True self.backend should be a new instance of the redis backend. 

------testpy3 2021-04-22 23:11:28,691 ERROR   [pas.plugins.ldap:101][waitress-1] Error in enumerateUsers
Traceback (most recent call last):
  File "/opt/plone/buildout/src/pas.plugins.ldap/src/pas/plugins/ldap/plugin.py", line 83, in _wrapper
    result = original_method(self, *args, **kwargs)
  File "/opt/plone/buildout/src/pas.plugins.ldap/src/pas/plugins/ldap/plugin.py", line 425, in enumerateUsers
    criteria=kw, attrlist=("login",), exact_match=exact_match
  File "/opt/plone/buildout-cache/eggs/node.ext.ldap-1.0b12-py3.6.egg/node/ext/ldap/ugm/_api.py", line 702, in search
    cookie=cookie
  File "/opt/plone/buildout-cache/eggs/node.ext.ldap-1.0b12-py3.6.egg/node/ext/ldap/ugm/_api.py", line 664, in raw_search
    cookie=cookie
  File "/opt/plone/buildout-cache/eggs/node-0.9.25-py3.6.egg/node/utils.py", line 250, in wrapped
    f_result = func(*args, **kws)
  File "/opt/plone/buildout-cache/eggs/node.ext.ldap-1.0b12-py3.6.egg/node/ext/ldap/_node.py", line 521, in search
    cookie=cookie
  File "/opt/plone/buildout-cache/eggs/node.ext.ldap-1.0b12-py3.6.egg/node/ext/ldap/session.py", line 59, in search
    cookie
  File "/opt/plone/buildout-cache/eggs/node.ext.ldap-1.0b12-py3.6.egg/node/ext/ldap/base.py", line 260, in search
    args
  File "/opt/plone/buildout/src/pas.plugins.ldap/src/pas/plugins/ldap/cache.py", line 89, in getData
    ret = self.get(key, force_reload=force_reload)
  File "/opt/plone/buildout/src/pas.plugins.ldap/src/pas/plugins/ldap/cache.py", line 100, in get
    res = self._client.get(key)
  File "/opt/plone/buildout-cache/eggs/dogpile.cache-1.1.2-py3.6.egg/dogpile/cache/region.py", line 767, in get
    value
  File "/opt/plone/buildout-cache/eggs/dogpile.cache-1.1.2-py3.6.egg/dogpile/cache/region.py", line 790, in value_fn
    value.metadata["ct"]
AttributeError: 'bytes' object has no attribute 'metadata'

**Comment by enfold-josh** [comment] 2021-04-27 21:48
@dataflake I have changed our test zope to run with a single thread and I have not see the error so far.

**Comment by runyaga** [comment] 2021-04-27 23:13
@dataflake its probable that the threadlocal in the pas ldap cache is causing issues.  if you look at https://github.com/enfold/collective.rediscache/blob/master/collective/rediscache/cachemanager.py there is no threadlocal being used since dogpile is reentrant.

**Comment by dataflake** [comment] 2021-04-28 09:11
I am having a really hard time reproducing the error locally so it's hard to tell if the following changes I put into 82b3a66a276ccec4c63c8dbfecfadaf8e8cb9682 really make a difference:

- implemented `get_serialized` and `set_serialized` on the `LoggingProxy` class because I saw a different traceback one time due to the missing implementation
- changed `setTimeout` on the `PasLdapRedisCache` class to only reconfigure the backend if the passed-in timeout differs from the timeout already set. This cuts down on a ton of reconfiguration calls.
- store the cache object for Redis directly on the `cacheProviderFactory` class to prevent issues with the thread local

Please test the latest `master` and let me know if you still see issues.

**Comment by runyaga** [comment] 2021-04-29 21:19
we have run some e2e tests on the machine and can no longer reproduce the error. closing.

**Closed as completed by runyaga** 2021-04-29 21:19 UTC
